export const seedData = {
  noteNames: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
  enharmonicNames: [
    'C',
    'Db',
    'D',
    'Eb',
    'E',
    'F',
    'Gb',
    'G',
    'Ab',
    'A',
    'Bb',
    'B',
  ],

  chordQualities: [
    {
      name: 'Major',
      symbol: '',
      intervals: [0, 4, 7],
      category: 'basic',
    },
    {
      name: 'Minor',
      symbol: 'm',
      intervals: [0, 3, 7],
      category: 'basic',
    },
    {
      name: 'Diminished',
      symbol: 'dim',
      intervals: [0, 3, 6],
      category: 'basic',
    },
    {
      name: 'Augmented',
      symbol: 'aug',
      intervals: [0, 4, 8],
      category: 'basic',
    },
    {
      name: 'Dominant 7th',
      symbol: '7',
      intervals: [0, 4, 7, 10],
      category: 'seventh',
    },
    {
      name: 'Major 7th',
      symbol: 'maj7',
      intervals: [0, 4, 7, 11],
      category: 'seventh',
    },
    {
      name: 'Minor 7th',
      symbol: 'm7',
      intervals: [0, 3, 7, 10],
      category: 'seventh',
    },
    {
      name: 'Minor Major 7th',
      symbol: 'mM7',
      intervals: [0, 3, 7, 11],
      category: 'seventh',
    },
    {
      name: 'Half-diminished 7th',
      symbol: 'm7b5',
      intervals: [0, 3, 6, 10],
      category: 'seventh',
    },
    {
      name: 'Diminished 7th',
      symbol: 'dim7',
      intervals: [0, 3, 6, 9],
      category: 'seventh',
    },
    {
      name: 'Sus4',
      symbol: 'sus4',
      intervals: [0, 5, 7],
      category: 'suspended',
    },
    {
      name: 'Sus2',
      symbol: 'sus2',
      intervals: [0, 2, 7],
      category: 'suspended',
    },
    {
      name: '6th',
      symbol: '6',
      intervals: [0, 4, 7, 9],
      category: 'sixth',
    },
    {
      name: 'Minor 6th',
      symbol: 'm6',
      intervals: [0, 3, 7, 9],
      category: 'sixth',
    },
    {
      name: '9th',
      symbol: '9',
      intervals: [0, 4, 7, 10, 14],
      category: 'extended',
    },
    {
      name: 'Major 9th',
      symbol: 'maj9',
      intervals: [0, 4, 7, 11, 14],
      category: 'extended',
    },
    {
      name: 'Minor 9th',
      symbol: 'm9',
      intervals: [0, 3, 7, 10, 14],
      category: 'extended',
    },
    {
      name: 'add9',
      symbol: 'add9',
      intervals: [0, 4, 7, 14],
      category: 'extended',
    },
    {
      name: '6/9',
      symbol: '6/9',
      intervals: [0, 4, 7, 9, 14],
      category: 'extended',
    },
  ],

  scales: [
    {
      name: 'Major',
      pattern: [0, 2, 4, 5, 7, 9, 11],
    },
    {
      name: 'Natural Minor',
      pattern: [0, 2, 3, 5, 7, 8, 10],
    },
    {
      name: 'Harmonic Minor',
      pattern: [0, 2, 3, 5, 7, 8, 11],
    },
    {
      name: 'Melodic Minor',
      pattern: [0, 2, 3, 5, 7, 9, 11],
    },
    {
      name: 'Dorian',
      pattern: [0, 2, 3, 5, 7, 9, 10],
    },
    {
      name: 'Phrygian',
      pattern: [0, 1, 3, 5, 7, 8, 10],
    },
    {
      name: 'Lydian',
      pattern: [0, 2, 4, 6, 7, 9, 11],
    },
    {
      name: 'Mixolydian',
      pattern: [0, 2, 4, 5, 7, 9, 10],
    },
    {
      name: 'Locrian',
      pattern: [0, 1, 3, 5, 6, 8, 10],
    },
  ],

  scaleDegrees: [
    {
      scaleName: 'Major',
      degree: 1,
      name: 'Tonic',
      romanNumeral: 'I',
      quality: 'major',
      function: 'tonic',
    },
    {
      scaleName: 'Major',
      degree: 2,
      name: 'Supertonic',
      romanNumeral: 'ii',
      quality: 'minor',
      function: 'subdominant',
    },
    {
      scaleName: 'Major',
      degree: 3,
      name: 'Mediant',
      romanNumeral: 'iii',
      quality: 'minor',
      function: 'tonic',
    },
    {
      scaleName: 'Major',
      degree: 4,
      name: 'Subdominant',
      romanNumeral: 'IV',
      quality: 'major',
      function: 'subdominant',
    },
    {
      scaleName: 'Major',
      degree: 5,
      name: 'Dominant',
      romanNumeral: 'V',
      quality: 'major',
      function: 'dominant',
    },
    {
      scaleName: 'Major',
      degree: 6,
      name: 'Submediant',
      romanNumeral: 'vi',
      quality: 'minor',
      function: 'tonic',
    },
    {
      scaleName: 'Major',
      degree: 7,
      name: 'Leading Tone',
      romanNumeral: 'vii°',
      quality: 'diminished',
      function: 'dominant',
    },

    {
      scaleName: 'Natural Minor',
      degree: 1,
      name: 'Tonic',
      romanNumeral: 'i',
      quality: 'minor',
      function: 'tonic',
    },
    {
      scaleName: 'Natural Minor',
      degree: 2,
      name: 'Supertonic',
      romanNumeral: 'ii°',
      quality: 'diminished',
      function: 'subdominant',
    },
    {
      scaleName: 'Natural Minor',
      degree: 3,
      name: 'Mediant',
      romanNumeral: 'III',
      quality: 'major',
      function: 'tonic',
    },
    {
      scaleName: 'Natural Minor',
      degree: 4,
      name: 'Subdominant',
      romanNumeral: 'iv',
      quality: 'minor',
      function: 'subdominant',
    },
    {
      scaleName: 'Natural Minor',
      degree: 5,
      name: 'Dominant',
      romanNumeral: 'v',
      quality: 'minor',
      function: 'dominant',
    },
    {
      scaleName: 'Natural Minor',
      degree: 6,
      name: 'Submediant',
      romanNumeral: 'VI',
      quality: 'major',
      function: 'subdominant',
    },
    {
      scaleName: 'Natural Minor',
      degree: 7,
      name: 'Subtonic',
      romanNumeral: 'VII',
      quality: 'major',
      function: 'dominant',
    },
  ],

  progressionPatterns: [
    {
      name: 'I-IV-V',
      romanNumerals: ['I', 'IV', 'V'],
      emotion: 'happy, traditional',
    },
    {
      name: 'I-V-vi-IV',
      romanNumerals: ['I', 'V', 'vi', 'IV'],
      emotion: 'emotional, uplifting',
    },
    {
      name: 'ii-V-I',
      romanNumerals: ['ii', 'V', 'I'],
      emotion: 'jazzy, resolved',
    },
    {
      name: 'vi-IV-I-V',
      romanNumerals: ['vi', 'IV', 'I', 'V'],
      emotion: 'sentimental',
    },
    {
      name: 'I-vi-IV-V',
      romanNumerals: ['I', 'vi', 'IV', 'V'],
      emotion: 'classic rock, nostalgic',
    },
    {
      name: 'i-iv-v',
      romanNumerals: ['i', 'iv', 'v'],
      emotion: 'melancholic',
    },
    {
      name: 'i-VI-III-VII',
      romanNumerals: ['i', 'VI', 'III', 'VII'],
      emotion: 'sad, dramatic',
    },
  ],

  genres: [
    { name: 'Rock' },
    { name: 'Pop' },
    { name: 'Jazz' },
    { name: 'Blues' },
    { name: 'Classical' },
    { name: 'Electronic' },
    { name: 'Hip Hop' },
    { name: 'Country' },
    { name: 'R&B' },
    { name: 'Folk' },
  ],

  genreProgressions: [
    { genreName: 'Rock', progressionName: 'I-V-vi-IV' },
    { genreName: 'Rock', progressionName: 'I-vi-IV-V' },
    { genreName: 'Pop', progressionName: 'I-IV-V' },
    { genreName: 'Pop', progressionName: 'I-V-vi-IV' },
    { genreName: 'Pop', progressionName: 'vi-IV-I-V' },
    { genreName: 'Pop', progressionName: 'I-vi-IV-V' },
    { genreName: 'Jazz', progressionName: 'ii-V-I' },
    { genreName: 'Blues', progressionName: 'I-IV-V' },
    { genreName: 'Classical', progressionName: 'I-IV-V' },
    { genreName: 'Classical', progressionName: 'I-vi-IV-V' },
    { genreName: 'Electronic', progressionName: 'I-V-vi-IV' },
    { genreName: 'Folk', progressionName: 'I-IV-V' },
    { genreName: 'Folk', progressionName: 'I-vi-IV-V' },
  ],

  progressions: [
    {
      keyName: 'C Major',
      genreName: 'Pop',
      patternName: 'I-V-vi-IV',
      chordSequence: ['C', 'G', 'Am', 'F'],
      measures: 4,
    },
    {
      keyName: 'G Major',
      genreName: 'Rock',
      patternName: 'I-vi-IV-V',
      chordSequence: ['G', 'Em', 'C', 'D'],
      measures: 4,
    },
    {
      keyName: 'A Minor',
      genreName: 'Folk',
      patternName: 'i-VI-III-VII',
      chordSequence: ['Am', 'F', 'C', 'G'],
      measures: 4,
    },
    {
      keyName: 'D Major',
      genreName: 'Jazz',
      patternName: 'ii-V-I',
      chordSequence: ['Em7', 'A7', 'Dmaj7'],
      measures: 4,
    },
    {
      keyName: 'F Major',
      genreName: 'Pop',
      patternName: 'I-V-vi-IV',
      chordSequence: ['F', 'C', 'Dm', 'Bb'],
      measures: 4,
    },
  ],
};
